### ISSUE TITLE
Make Calendar config driven

### ISSUE THREAD

**Issue by NorthIsUp** [SugarPushCode/920-special-static#19]
The calendar is a PITA to update on a weekly basis, so lets focus on making this better.
# Phase 1: Config file driven model

Provide a simple config file that will allow for adding a title, name, and date and have this information reflected on the website. The file will be editable on github.
- [x] Announce a special event with config
- [x] Change DJs with config
- [x] Change Instructors with config
# DB driven model

Provide an admin UI where you can click buttons and it will set the djs/teachers/etc.
- [ ] Announce a special event with admin
- [ ] Change DJs with admin
- [ ] Change Instructors with admin

**Comment by kirktarou** [comment]
The 'djs' section of the config file has a date associated with each entry, but the 'schedule' section does not. It looks like we need to add some logic that shows the DJs and schedule for the current month and next month (if it exists in the config file). This will mean changing the format of the 'schedule' data to include a month & year field and adding the display logic to to the templates.
